services:
  backend:
    image: ghcr.io/profiidev/images/rust-musl-watch:main
    volumes:
      - ./backend:/app
    networks:
      - nginx
    tty: true
    entrypoint: ['tini', '--']
    command: ['cargo', 'watch', '-x', 'run']

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '1421:1420'
    networks:
      - nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - backend

networks:
  nginx:

volumes:
  logs:
