name: Auto Merge PR with Release Version

on:
  pull_request:
    types:
      - labeled

jobs:
  merge:
    if: ${{ github.event.label.name == 'release-version' && github.event.pull_request.user.login == 'Profiidev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PR
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
