name: Cache App

on:
  release:
    types:
      - published

jobs:
  cache-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        if: github.event_name != 'pull_request'
        with:
          name: profidev
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: Run build
        run: nix build -Lv
      - name: Cache results
        run: readlink result | cachix push profidev
