name: Cache App

on:
  pull_request:
  release:
    types:
      - published

jobs:
  cache-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
      - name: Install Hibernation CLI
        uses: profiidev/hibernation@d1d0857b79670ea9edb16431850bff98f93cdcbe # v0
        if: github.event_name != 'pull_request'
        with:
          url: ${{ secrets.HIBERNATION_URL }}
          token: ${{ secrets.HIBERNATION_TOKEN }}
          signing-key: ${{ secrets.HIBERNATION_SIGNING_KEY }}

      - name: Run build
        run: nix build . -Lv --print-out-paths --accept-flake-config

      - name: Cache results
        if: github.event_name != 'pull_request'
        run: hibernation push projects $(readlink result)
