name: Cache App

on:
  pull_request:
  release:
    types:
      - published

jobs:
  cache-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set version
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          JSON_FILE="app/src-tauri/tauri.conf.json"
          RAW_TAG="${{ github.event.release.tag_name }}v0.1.0"
          NEW_VERSION="${RAW_TAG#v}"
          echo "Updating version in $JSON_FILE to $NEW_VERSION"
          jq ".version = \"$NEW_VERSION\"" "$JSON_FILE" > $JSON_FILE.temp && mv $JSON_FILE.temp "$JSON_FILE"
          jq -s 'reduce .[] as $item ({}; . * $item)' "$JSON_FILE" "$JSON_FILE.release" > "$JSON_FILE.result"
          mv "$JSON_FILE.result" "$JSON_FILE"
          cat "$JSON_FILE"

      - uses: cachix/cachix-action@v15
        if: github.event_name == 'pull_request'
        with:
          name: profidev
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run build
        run: nix build -Lv
      - name: Run Check
        run: nix flake check
