name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release-tag:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-version') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          VERSION=${{ github.event.pull_request.head.ref }}
          VERSION=${VERSION#chore/release-version-}
          echo "Creating tag for version $VERSION"
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Update latest tag
        run: |
          git tag -f latest
          git push origin -f latest


  create-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            Release version ${{ github.ref_name }} has been created.
          generate_release_notes: true
